# Brycen Martin, Jonathan Laughlin and Shane Snediker
# Dr. Jones CS473
# Genetic Algorithm Final Project
# Updated December 17, 2020

# City Class defines our problem space: a mini portion of Spokane

# Access Google's Spokane City Map API
#import googlemaps 
#from datetime import datetime
#from googlemaps import Client
#gmaps = Client(key='AIzaSyCFcf_BmN1Qm1q-a3yy07RXtPHMgOiyZ-w')

class City:
    ########################################
    # MEMBER VARIABLES
    ########################################

    # Initial bot grid parameters
    DELIVERY_LOC = [4, 4]         # The location where the bot is delivering
    BEGIN_LOC = [1, 13]              # The location from which the bot is delivering

    # Default orientation is for agents to spawn in facing EAST
    # We use the unit circle for directional defintionf (0: E, 90: N, 180: W, 270: S)
    CITY_START_ORIENTATION = 0

    # We need to scale up our graphical display grid into larger grid squares 
    # This sets the WIDTH and HEIGHT of each grid square
    CELL_SIZE = 10

    # Set the WIDTH and HEIGHT of the pop up screen
    CITY_SIZE = [1170, 360]

    ################## 2 DIMENSIONAL ARRAY HOLDING OUR CITY STREET DATA #######################################   
    
    # HERE WE CREATE A 2 DIMENSIONAL ARRAY TO HOLD THE MINI CITY STREET INFORMATION
    # THIS WILL BE A LARGE AREA OF ARRAYS HOLDING ALL OF THE INTERSECTION DATA FROM 
    # OUR MINI CITY.  EACH ROW IN THE 2 DIMENSIONAL ARRAY CORRESPONDS WITH A WEST/EAST
    # STREET IN OUR MINI CITY, WHILE EACH COLUMN CORRESPONDS TO A NORTH/SOUTH STREET.
    # OUR CITY WILL BE  WILL BE 1170 UNITS IN THE X-DIRECTION AND 360 UNITS IN THE Y-DIRECTION
    # WHILE THE FOLLOWING DEFINITION REPRESENTS THE FILLING OF EVERY CELL IN THE 1170X360 CITY,
    # WE SCALE THE GRID SO THAT EVERY GRID CELL LOCATION WILL BE A 10X10 PIXEL BLOCK
    # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    #         Monroe                                 Lincoln                                Post                            Wall                             Howard                               Stevens                            Washington                             Whitehouse                           Calispel                            Normandie                             Atlantic                            Division
    CITY_GRID = [
    [[False, True, True, False, True],    [False, True, True, True, True],     [False, True, True, True, True], [False, True, True, True, True],   [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [False, True, False, True, True]], 
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, False, True, True, True],     [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, False, True, True, True],     [True, False, True, True, True],     [True, False, True, True, True],     [True, True, False, True, True]], 
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [False, True, True, True, True],     [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, True, True, True, True],     [False, False, True, True, False],   [False, True, True, True, True],     [True, True, False, True, True]], 
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, False, True, True, True],     [False, True, True, True, True],     [True, False, True, True, True],     [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, False, True, True, True],     [False, False, True, True, False],   [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True],     [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [True, True, False, False, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True],     [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [True, True, False, False, True]],  
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [True, True, False, True, True]],      # Queen
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, False, True, True, True],     [True, True, False, True, True]],      # Wabash
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, False, True, True, True],     [False, True, True, True, True],     [True, True, False, True, True]],      # Wellesley
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True],     [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [True, True, False, True, True]],      # Princeton
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, False, True, True, True],     [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, False, True, True],     [True, True, False, False, True]],     # Heroy
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [False, True, True, True, True],     [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, True, True, True, True],     [False, True, True, True, True],     [True, True, True, True, True],      [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],      # Rockwell
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, False, True, True, True],     [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True],     [False, False, False, False, False], [True, True, False, False, True]],
    [[True, True, True, False, True],     [True, False, True, True, True],     [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, False, True, True, True],     [True, True, True, True, True],      [True, False, True, True, True],     [True, True, True, True, True],      [True, True, True, True, True],      [False, True, True, True, True],     [True, True, False, True, True]],      # Garland
    [[True, True, True, False, True],     [False, False, True, True, False],   [True, True, True, True, True],  [True, False, True, True, True],   [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],
    [[True, True, True, False, True],     [False, False, True, True, False],   [True, True, True, True, True],  [False, False, True, True, False], [True, True, True, True, True],      [False, False, True, True, False],   [True, True, False, True, True],     [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [True, True, False, False, True]],
    [[True, True, True, False, True],     [False, False, True, True, False],   [True, True, True, True, True],  [False, False, True, True, False], [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],        
    [[False, False, False, False, False], [False, False, False, False, False], [True, True, True, False, True], [False, False, True, True, False], [True, False, True, True, True],     [False, False, True, True, False],   [True, False, True, True, True],     [False, False, True, True, False],   [True, False, True, True, True],     [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],      # Glass
    [[True, True, True, False, True],     [False, True, True, True, True],     [True, True, True, True, True],  [False, False, True, True, False], [False, True, True, True, True],     [False, True, True, True, True],     [False, True, True, True, True],     [False, False, True, True, False],   [False, True, True, True, True],     [False, True, True, True, True],     [False, True, False, True, True],    [True, True, False, False, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [False, False, True, True, False], [True, True, True, True, True],      [True, True, True, True, True],      [False, True, False, True, True],    [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [True, True, False, False, True]],     # Alice
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [False, True, True, True, True],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [False, True, False, True, True],    [False, False, False, False, False], [True, True, False, False, True]],     # Dalton
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, False, True, True, True],     [True, True, True, True, True],      [True, False, True, True, True],     [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [False, True, True, True, True],     [True, True, False, True, True]],
    [[False, False, False, False, False], [False, False, False, False, False], [True, True, True, False, True], [True, False, True, True, True],   [False, False, True, True, False],   [True, False, True, True, True],     [False, False, True, True, False],   [False, False, True, True, False],   [True, False, True, True, True],     [True, True, True, True, True],      [True, True, False, True, True],     [True, True, False, False, True]],
    [[False, False, False, False, False], [False, False, False, False, False], [True, True, True, False, True], [False, True, True, True, True],   [False, True, True, True, True],     [False, False, True, True, False],   [False, True, True, True, True],     [False, False, True, True, False],   [False, False, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],      # Waverly
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [False, False, True, True, False],   [False, True, True, True, True],     [True, False, True, True, True],     [True, True, True, True, True],      [True, True, False, True, True]],
    [[False, False, False, False, False], [False, False, False, False, False], [True, True, True, False, True], [True, True, True, True, True],    [True, True, True, True, True],      [False, True, True, True, True],     [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [False, True, True, True, True],     [True, True, True, True, True],      [True, True, False, True, True]],      # Buckeye
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, False, True, True],   [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [True, True, False, False, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],      # York
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, False, True, True, True],     [True, True, True, True, True],      [True, True, False, True, True]],      # Mansfield
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [False, True, True, True, True],     [True, True, True, True, True],      [True, True, False, True, True]],      # Knox
    [[True, True, True, False, True],     [True, True, True, True, True],      [True, True, True, True, True],  [True, True, True, True, True],    [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [False, False, True, True, False],   [True, True, True, True, True],      [True, True, True, True, True],      [True, True, True, True, True],      [True, True, False, True, True]],      # Shannon
    [[True, False, True, False, True],    [True, False, True, True, True],     [True, False, True, True, True], [True, False, True, True, True],   [True, False, True, True, True],     [True, False, True, True, True],     [True, False, True, True, True],     [False, False, True, True, False],   [True, False, True, True, True],     [True, False, True, True, True],     [True, False, True, True, True],     [True, False, False, True, True]]]     # Indiana
    


#################################################################################################

#      THE MISCELLANEOUS DATA BELOW MAY GET WORKED BACK INTO OUR PROGRAM 


#################### LIST OF WEST STREETS #########################################################

    # All North/South streets west of Division street
    #NorthW = ['N Monroe St', 'N Lincoln St', 'N Post St', 'N Wall St', 'N Howard St', 'N Stevens St', 'N Washington St', 'N Whitehouse St', 'N Calispel St', 'N Normandie St', 'N Atlantic St', 'N Division St']
    # All East/West streets west of Division street
    #WestE = ['W Francis Ave', 'W Dalke Ave', 'W Central Ave', 'W Columbia Ave', 'W Joseph Ave', 'W Nebraska Ave', 'W Rowan Ave', 'W Everett Ave', 'W Queen Ave', 'W Wabash Ave', 'W Wellesley Ave', 'W Princeton Ave', 'W Heroy Ave', 'W Longfellow Ave', 'W Rockwell Ave', 'W Lacrosse Ave', 'W Walton Ave', 'W Garland Ave', 'W Providence Ave', 'W Kiernan Ave', 'W Gordon Ave', 'W Glass Ave', 'W Cora Ave', 'W Alice Ave', 'W Dalton Ave', 'W Euclid Ave', 'W Park Pl', 'W Waverly Pl', 'W Cleveland Ave', 'W Buckeye Ave', 'W Chelan Ave', 'W York Ave', 'W Jackson Ave', 'W Carlisle Ave', 'W Montgomery Ave', 'W Mansfield Ave', 'W Knox Ave', 'W Shannon Ave', 'W Indiana Ave']

################### LIST OF EAST STREETS ########################################################

# All North/South streets east of Division street
#NorthE = ['N Division St', 'N Ruby St', 'N Mayfair St', 'N Lidgerwood St', 'N Astor St', 'N Addison St', 'N Wiscomb St', 'N Standard St', 'N Dakota St', 'N Cincinnati St', 'N Hamilton St', 'N Nevada St', 'N Columbus St', 'N Morton St', 'N Perry St', 'N Hogan St', 'N Helena St', 'N Madelia St', 'N Pittsburg St', 'N Magnolia St', 'N Napa St', 'N Martin St', 'N Crestline St']
# All East/West streets east of Division street
#EastW = ['E Francis', 'E Decatur Ave', 'E Dalke Ave','E Bismark Ave', 'E Central Ave', 'E Columbia Ave', 'E Joseph Ave', 'E Nebraska Ave', 'E Rowan Ave', 'E North Ave', 'E Sanson Ave', 'E Everett Ave', 'E Crown Ave', 'E Queen Ave', 'E Olympic Ave', 'E Wabash Ave', 'E Broad Ave', 'E Wellesley Ave', 'E Hoffman Ave', 'E Princeton Ave', 'E Heroy Ave', 'E Longfellow Ave', 'E Rich Ave', 'E Rockwell Ave', 'E Lacrosse Ave', 'E Walton Ave', 'E Garland Ave', 'E Empire Ave', 'E Providence Ave', 'E Kiernan Ave', 'E Gordan Ave', 'E Glass Ave', 'E Courtland Ave', 'E Bridgeport Ave', 'Liberty Ave', 'E Dalton Ave', 'E Euclid Ave', 'E Fairview Ave', 'E Cleveland Ave', 'E North Foothills Dr', 'E Grace Ave', 'E Buckeye Ave', 'E Marietta Ave', 'E Jackson Ave', 'E Carlisle Ave', 'E Montgomery Ave', 'E Illinois Ave', 'E Ermina Ave', 'E Baldwin Ave', 'E Indiana Ave']

################## INTERSECTION INFO FOR EASTSIDE STREETS #######################################
#                  N Division St                            N Ruby St                               N Mayfair St                               N Lidgerwood St                             N Astor St                            N Addison St                           N Wiscomb St                            N Standard St                               N Dakota St                            N Cincinnati St                           N Hamilton St                             N Nevada St                            N Columbus St                                N Morton St                                 N Perry St                            N Hogan St                                      N Helena St                            N Pittsburg St                               N Magnolia St                              N Napa St                              N Martin St                          N Crestline St
#East = [
#[[False,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,True,True,True,True], [False,True,True,True,True], [False,True,True,True,True], [False,True,True,True,True], [False,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,False,True,True,False], [False,True,False,True,True]],                                                                     # Francis
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True]],                                                   # Decatur
#[[True,True,True,True,True], [False, True, True, True, True], [True, True,True,True,True], [True, True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True]],                                                                                # Dalke
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True]],                                                   # Bismark      
#[[True,True,True,True,True], [True,False,True,True,True], [True,False,True,True,True], [True,True,True,True,True], [True,False,True,True,True], [True,True,True,True,True], [True,False,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,False,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [True,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True]],                                                                                  # Central  
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True]],                                                         # Columbia
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [False,False,True,True,False], [True,True,False,True,True]],                                                       # Joseph
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [False,False,True,True,False], [True,True,False,True,True]],                                                    # Nebraska
#[[True,False,True,False,True], [False,False,False,False,False], [False,True,True,True,True], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [False, True, True, True, False], [True,True,False,True,True]],                                                # Rowan
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, False, True, True], [True, True, True, False, True], [True, True, False, True, True], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False]],                                  # North       
#[[True,False,True,False,True], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, False, True, True], [True, True, True, False, True], [True, True, False, True, True], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False]],                                      # Sanson   
#[[True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,True,True,True], [True, True, True, True, True], [True,True,False,True,True]],                                                                  # Everett          
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, False, True, True], [True,True,False,False,False], [True, True, False, False, False], [False,False,False,False,False]],                                                       # Crown   
#[[True,True,True,True,True], [False,False,True,True,False], [True,False,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,False,False,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],                                                             # Queen
#[[True,True,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, False, True, True], [True,True,False,False,False], [True, True, False, False, False], [False,False,False,False,False]],                                              # Olympic
#[[True,True,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],                                                     # Wabash        
#[[True,True,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, False, True, True], [True,True,False,False,False], [True, True, False, False, False], [False,False,False,False,False]],                                              # Broad
#[[True,True,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True],  [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False],  [True, False, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [True,True,False,True,True]],                                                          # Wellesley 
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,False,True], [False,False,True,True,False], [False, False, False, False, False], [True, True, True, False, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                 # Hoffman 
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,False,True], [False,False,True,True,False], [False, False, False, False, False], [True, True, False, False, False], [False, False, False, False, False], [True,True,False,False,False], [False, False, False, False, False], [False,False,False,False,False]],                                        # Princeton
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,False,True], [False,False,True,True,False], [False, True, True, False, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                     # Heroy 
#[[True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,False,True], [False,False,True,True,False], [True, True, True, False, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                      # Longfellow
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, True, True, True, True], [True,True,False,True,True]],                                                          # Rich
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, False, True, True], [True, True, False, False, False], [False,False,False,False,False]],                                                   # Rockwell
#[[True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True],  [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [False, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],                                                             # Lacrosse 
#[[True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],                                                               # Walton
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [False,True,False,True,True]],                                                           # Garland   
#[[True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                          # Empire
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, False, True, True, True], [False, False, True, True, False], [False,True,False,True,True]],                                                      # Providence
#[[True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True], [False,False,False,False,False], [True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,False,True,True], [False,False,True,True,False], [True, True, False, False, False], [True, True, False, False, False], [False, False, False, False, False], [False,False,False,False,False], [False, False, False, False, False], [False,False,False,False,False]],                                     # Kiernan
#[[True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,False,True,True], [False,False,True,True,False], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [False, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                        # Gordon
#[[True,True,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                            # Glass
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                           # Courtland
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                           # Bridgeport
#[[True,False,True,False,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                           # Liberty
#[[False,True,False,False,False], [False,False,False,False,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True, True, True, True, True], [True, True, True, True, True], [False, False, True, True, False], [True, True, True, True, True], [False, False, True, True, False], [True,True,False,True,True]],                                                       # Dalton
#[[False,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True, True, True, True, True], [True, True, False, False, False], [False, False, False, False, False], [True, True, False, False, False], [False, False, False, False, False], [False,False,False,False,False]],                                                    # Euclid
#[[False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,True,True], [False,False,True,True,False], [True,False,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,False,True,True], [True,True,True,False,True], [True,True,False,True,True], [False,False,True,True,False], [False,False,True,True,False], [False,False,True,True,False], [True,True,True,False,True], [True,True,True,True,True], [True, False, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],                                                   # Fairview
#[[True,False,True,False,True], [True,False,True,False,True], [True,True,True,True,True], [False,False,False,False,False], [False,True,True,True,True], [False,False,True,True,False], [True,False,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,False,True,True], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False, False, False, False, False], [True, True, False, True, True], [False, False, False, False, False], [True, True, False, False, False], [True, True, False, False, False], [False,False,False,False,False]],                        # Cleveland
#[[False,True,True,True,True], [True,False,True,True,True], [True,False,True,True,True],[False,False,True, True,False], [True,False,True,True,True], [False,False,True,True,False], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [False, False, True, True, False], [True, True, True, True, True], [False, True, True, True, True], [True, True, True, True, True], [False, True, True, True, True], [True,True,False,True,True]],                                                            # North Foothills Dr   
#[[False,True,False,False,False], [True,False,False,False,False], [False,False,True,True,False], [False,False,False,False,False], [True,True,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,False,False,False], [True,True,False,False,False], [True,True,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [False, False, False, False, False], [True, True, True, False, True], [False, False, True, True, False], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],        # Grace
#[[False,True,False,False,False], [True,False,False,False,False], [False,False,True,True,False], [False,False,False,False,False], [True,True,False,False,False], [False,False,False,False,False], [False,False,True,True,False], [True,True,False,True,True], [True,True,False,False,False], [True,True,False,False,False], [False,False,False,False,False], [False,False,True,True,False], [False,False,True,True,False], [False,False,True,True,False], [True,True,True,False,True], [True,True,True,True,True], [False, False, True, True, False], [True, True, True, True, True], [False, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True,True,False,True,True]],                                # Buckeye     
#[[False,True,False,False,False], [True,False,False,False,False], [False,False,True,True,False], [False,False,False,False,False], [True,True,False,False,False], [False,False,False,False,False], [False,False,False,False,False], [True,True,False,False,False], [True,True,False,False,False], [True,True,True,False,True], [True,True,True,True,True], [True,True,True,True,True], [False,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False, False, True, True, False], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, False, True, True, True], [True,True,False,True,True]],                                           # Marietta 
#[[False,True,True,False,True], [True,False,True,True,True], [False,False,True,True,False], [False,False,True, True,False], [False,True,True,True,True], [False,True,True,True,True], [False,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False, False, True, True, False], [True, True, True, True, True], [True, True, False, True, True], [True, True, False, False, False], [False, False, False, False, False], [False,False,False,False,False]],                                                        # Jackson
#[[False,True,True,True,True], [True,False,False,True,True], [False,False,False,False,False], [False,False,False,False,False], [True,True,True,False,True], [True,True,True,True,True], [True,False,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,False,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False, False, True, True, False], [True, True, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False,False,False,False,False]],                                            # Carlisle
#[[False,True,True,False,True], [True,False,True,True,True], [False,False,True,True,False], [False,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,False,True,True], [False,False,False,False,False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False,False,False,False,False]],                                     # Montgomery
#[[False,True,False,False,False], [True,False,False,False,False], [False,False,False,False,False],[True,True,False,False,False], [True,True,False,False,False], [True,True,False,False,False], [False,False,False,False,False], [True,True,False,False,False], [True,True,True,False,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,False,True,True,True], [False, False, True, True, False], [True, False, True, True, True], [True, False, True, True, True], [True, False, True, True, True], [False, False, True, True, False], [True,False,False,True,True]],                                         # Illinois
#[[False,True,True,False,True], [True,False,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,False,True,True], [False,False,False,False,False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False,False,False,False,False]],                                      # Ermina
#[[False,True,True,False,True], [True,False,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,False,True,True], [True,True,True,False,True], [True,True,True,True,True], [True,True,True,True,True], [False,False,True,True,False], [True,True,True,True,True], [True,True,True,True,True], [True,True,False,True,True], [False,False,False,False,False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False],[False, False, False, False, False], [False, False, False, False, False], [False,False,False,False,False]],                                     # Baldwin
#[[False,True,True,True,True], [True,False,True,True,True], [False,False,True,True,False], [True,False,True,True,True], [True,False,True,True,True], [True,False,True, True,True], [False,False,True,True,False], [True,False,True,True,True], [True,False,True,True,True], [True,False,True,True,True], [True,False,True,True,True], [False,False,True,True,False], [True,False,True,True,True], [True,False,True,True,True], [True,False,True,True,True], [False,False,True,True,False], [False, False, True, True, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False,False,False,False,False]]],                                # Indiana



# Geocoding an address
#geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')

# Look up an address with reverse geocoding
#reverse_geocode_result = gmaps.reverse_geocode((40.714224, -73.961452))
#directions = gmaps.distance_matrix('N Ruby St E Ermina Ave, Spokane, WA', 'N Ruby St E Baldwin, Spokane, WA') #directions('N Ruby St E Ermina Ave, Spokane, WA', 'N Ruby St E Baldwin, Spokane, WA')
#print(directions)  

#print("done")
#directions = directions[0]
#i=1
#for leg in directions['legs']:
#    startAddress = leg['start_address']
#    print("Start Address:", startAddress)
#    endAddress = leg['end_address']
#    distance = leg['distance']['text']
#    print("End Address:", endAddress)
#    print("Distance:", distance)
#    for step in leg['steps']:
#        html_instructions = step['html_instructions']
#        html_instructions = html_instructions.split('<b>')
#        html_instructions2 = ''
#        for each in html_instructions:
#            if(each != '<b>'):
#                html_instructions2 += each
#        html_instructions2 = html_instructions2.split('</b>')
#        html_instructions3 = ''
#        for each in html_instructions2:
#            if(each != '<b\>'):
#                html_instructions3 += each
#        print("STEP {} {}".format(i ,html_instructions3))
#        i = i+1